---
name: traefik

services:
  proxy:
    image: traefik:v3.5
    container_name: proxy
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./user.pass:/etc/traefik/user.pass
      - /run/docker.sock:/run/docker.sock
    restart: unless-stopped
    networks:
      proxynet:

networks:
  proxynet:
    external: true
