---
services:
  hello-1:
    image: bob2606/hello-http:0.8.33
    container_name: hello-1
    hostname: hello-1
    restart: unless-stopped
    networks:
      hellonet:
      proxynet:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxynet
      - traefik.http.routers.hello-1.rule=Host(`hello-1.stage.local`)
      - traefik.http.services.hello-1.loadbalancer.server.port=8080

  hello-2:
    image: bob2606/hello-http:0.8.33
    container_name: hello-2
    hostname: hello-2
    environment:
      - PORT=80
    networks:
      hellonet:
      proxynet:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxynet
      - traefik.http.routers.hello-2.rule=PathPrefix(`/hello-2`)
      - traefik.http.services.hello-2.loadbalancer.server.port=80
      - traefik.http.middlewares.striphello-2.stripprefix.prefixes=/hello-2
      - traefik.http.routers.hello-2.middlewares=striphello-2
    restart: unless-stopped

  hello-3:
    image: bob2606/hello-http:0.8.33
    container_name: hello-3
    hostname: hello-3
    restart: unless-stopped

networks:
  hellonet:
  proxynet:
    external: true
