---
name: lemp
services:
  www:
    image: nginx:1.28
    container_name: www
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx-conf:/etc/nginx/conf.d:ro
    networks:
      lempnet:
        ipv4_address: 172.20.0.100
    depends_on:
      - php
    restart: unless-stopped

  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./html:/var/www/html:ro
    networks:
      lempnet:
        ipv4_address: 172.20.0.110
    restart: unless-stopped

  db:
    image: mariadb:11.0
    container_name: mariadb
    environment:
      - MARIADB_DATABASE=stage
    env_file:
      - mariadb.env
    networks:
      lempnet:
        ipv4_address: 172.20.0.120
    volumes:
      - datadb:/var/lib/mysql
    restart: unless-stopped

volumes:
  datadb:

networks:
  lempnet:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.254
    driver_opts:
      com.docker.network.bridge.name: lempnet0
